# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WA7_Yadav_1702' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WA7_Yadav_1702
	pod "Alamofire"

  target 'WA7_Yadav_1702Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WA7_Yadav_1702UITests' do
    # Pods for testing
  end

end
