# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPod Setup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPod Setup
  pod 'Alamofire'

  target 'CocoaPod SetupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoaPod SetupUITests' do
    # Pods for testing
  end

end
